jwt:
  signature: prd-signature-key
  issuer: prd.whypie.authorization
  subject: resource-access
  audience: prd-client
  access-token-validity-in-seconds-term: 600 # access token의 유효 기간 : 10분
  refresh-token-validity-in-seconds-term: 1200 # refresh token의 유효 기간 : 20분